### ISSUE TITLE
Reorganize upsells

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle-wporg#109]
- [x] Remove current upsells
- [x] Add View Pro version button like here: https://github.com/justintadlock/trt-customizer-pro/blob/master/example-1/screenshot.png (Don't add that Theme name pro string , just a view pro version button)
- [x] Add a Theme Info section like on Sydney https://www.dropbox.com/s/n7d4qdp14ob3o5y/Screenshot%202016-10-05%2011.06.37.png?dl=0 with a View documentation link , demo link and View pro version link

**Comment by ineagu** [comment]
for 3rd "Add a Theme Info section like on Sydney " instead of view pro I would add : Free vs Pro and link to free vs pro doc

**Comment by abaicus** [comment]
@rodica-andronache @ineagu Where do you think we should add the theme info section inside the customizer?

![image](https://cloud.githubusercontent.com/assets/15010186/19149147/0deaee04-8bc9-11e6-8ea7-6c91bb948e50.png)

**Comment by abaicus** [comment]
![image](https://cloud.githubusercontent.com/assets/15010186/19150096/bc181bf6-8bcd-11e6-957d-c12180a45641.png)
How about this? :)

**Comment by ineagu** [comment]
Ok with theme info sus
