### ISSUE TITLE
Add siteorigin compatibility

### ISSUE THREAD

**Issue by claudiuvertistudio** [Codeinwp/shop-isle-wporg#121]
Codeinwp/shop-isle#248

**Comment by rodica-andronache** [comment]
i think you need to add the class .page-template-template-fullwidth-no-title also for this rule:
```
.siteorigin-panels .widget li:before {
display: none;
}
```

can you also please rename the template name from:
Template Name: Full width with no title template
to:
Template Name: Full width, no title (SiteOrigin Page builder Template)
