### ISSUE TITLE
Font increase and image issues with latest Woocommerce version

### ISSUE THREAD

**Issue by poonam9** [Codeinwp/shop-isle-wporg#138]
@rodica-andronache After recent Woocommerce update Shopisle theme' s font increases on shop and product page and product images also meesed up.

**Comment by ineagu** [comment]
@rodica-andronache this should be a major priority for us

**Comment by rodica-andronache** [comment]
@poonam9 thanks :) You can add all issues related to both Shop Isle and Shop Isle Pro here https://github.com/Codeinwp/shop-isle-pro/ as that is the repository that generates both versions. Just mention on which theme is happening

**Comment by poonam9** [comment]
@rodica-andronache the given URL is not working.

**Comment by rodica-andronache** [comment]
@poonam9 ok, sorry. That is a private repository. You can post the issues here :)

**Comment by poonam9** [comment]
Ok so this is still considerable or I have to post it again.

**Comment by rodica-andronache** [comment]
@poonam9 yes, we'll fix it. I just moved the issue there

**Comment by poonam9** [comment]
@rodica-andronache thanks :)

**Comment by poonam9** [comment]
@rodica-andronache 
Product image quick view is also not working.
