### ISSUE TITLE
New screenshot

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle-wporg#4]
@rodica-andronache commented on [Tue Mar 22 2016](https://github.com/Codeinwp/shop-isle/issues/167)

---

@abaicus commented on [Fri Apr 15 2016](https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-210488746)

@ineagu Mai e valabil issue-ul asta? 

---

@ineagu commented on [Fri Apr 15 2016](https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-210512861)

Cred ca da, nu stiu cum arata screenshot curent, daca e foarte ok, lasam asa

> On 15 apr. 2016, at 17:44, Andrei Băicuș <notifications@github.com> wrote:
> 
> @ineagu Mai e valabil issue-ul asta?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

---

@rodica-andronache commented on [Wed Apr 20 2016](https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-212393783)

@ineagu asa arata https://github.com/Codeinwp/shop-isle/blob/production/screenshot.png

---

@ineagu commented on [Wed Apr 20 2016](https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-212410036)

cred ca am putea avea ceva mai colorat putin si text mai fain pe acolo

On Wed, Apr 20, 2016 at 1:48 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> asa arata
> https://github.com/Codeinwp/shop-isle/blob/production/screenshot.png
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-212393783>
>

-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
@ineagu Ce parere ai despre asta? 

![screenshot](https://cloud.githubusercontent.com/assets/15010186/15648491/ba8e5288-2673-11e6-91e4-558674a4d04d.png)

**Comment by ineagu** [comment]
not really, incearca 4-5 idei, le pui in w.org admin si vezi care si cum
atrage.



On Mon, May 30, 2016 at 1:35 PM, Andrei Băicuș <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> Ce parere ai despre asta?
>
> [image: screenshot]
> <https://cloud.githubusercontent.com/assets/15010186/15648491/ba8e5288-2673-11e6-91e4-558674a4d04d.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-222473590>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DG6UbXdOSfi8gw3PEZ8fRaAgBMsgks5qGsuGgaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
![screenshot_0000](https://cloud.githubusercontent.com/assets/15010186/15668614/ee88e0b0-2724-11e6-9c80-650750352269.png)
![screenshot_0001](https://cloud.githubusercontent.com/assets/15010186/15668615/ee893330-2724-11e6-87d3-dd23206636ee.png)
![screenshot_0002](https://cloud.githubusercontent.com/assets/15010186/15668617/ee8ca902-2724-11e6-8adf-4c4f15931c2c.png)
![screenshot_0003](https://cloud.githubusercontent.com/assets/15010186/15668618/ee96b99c-2724-11e6-9cfe-88ea4e7d1fff.png)
![wporg_0000](https://cloud.githubusercontent.com/assets/15010186/15668616/ee892372-2724-11e6-9e05-3236ddfefe78.jpg)
![wporg_0001](https://cloud.githubusercontent.com/assets/15010186/15668613/ee887666-2724-11e6-8267-974ba6fca0f3.jpg)
![wporg_0002](https://cloud.githubusercontent.com/assets/15010186/15668620/eea22fac-2724-11e6-972c-2aef4ccabf3d.jpg)
![wporg_0003](https://cloud.githubusercontent.com/assets/15010186/15668619/ee9f8194-2724-11e6-915b-da91276e5956.jpg)

**Comment by ineagu** [comment]
mie mi se pare mai ok ultima, dar cu text mutat ceva mia sus si pus un mic
layer pe imagine sa se vada si textul ( in screenshot ). Totusi nu sunt
convins, problema principala e ca cu un screenshot de genul + un preview cu
blog, nu ai cum sa iti dai seama ca e tema de shop .

On Tue, May 31, 2016 at 10:44 AM, Andrei Băicuș <notifications@github.com>
wrote:

> Eu inclin catre 1 si 2.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-222627785>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DOJG4lwLjSoQ-q8QsrGl8BZkangfks5qG_T3gaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
poate sa incercam sa aratam pagina de shop , iar la imaginile produselor sa fie niste fete ?

**Comment by abaicus** [comment]
Acum trebuie sa punem in balanta functionalitatea cu designul. Eu cred ca putem incerca sa facem ce zice @rodica-andronache. Nu e neaparat rau. :)

**Comment by ineagu** [comment]
ok, as incerca ceva de unde sa reiasa clar ca e o tema shop ;P

2016-06-01 16:12 GMT+02:00 Andrei Băicuș <notifications@github.com>:

> Acum trebuie sa punem in balanta functionalitatea cu designul. Eu cred ca
> putem incerca sa facem ce zice @rodica-andronache
> <https://github.com/rodica-andronache>. Nu e neaparat rau. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-223004813>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DEKio95tq6ui1qMN2yo75St_Df72ks5qHZNKgaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
![screenshot_0004](https://cloud.githubusercontent.com/assets/15010186/15820880/f64b2f9a-2bf4-11e6-9f50-db41945b31ae.png)
![screenshot_0005](https://cloud.githubusercontent.com/assets/15010186/15820878/f64abe48-2bf4-11e6-953b-58bf0b03e3e1.png)
![wporg_0004](https://cloud.githubusercontent.com/assets/15010186/15820877/f64aab60-2bf4-11e6-8cbf-850c4e38c915.jpg)
![wporg_0005](https://cloud.githubusercontent.com/assets/15010186/15820879/f64ae756-2bf4-11e6-9c88-12874a209b31.jpg)

**Comment by abaicus** [comment]
@ineagu Ce zici? Sa mergem in directia asta?

**Comment by rodica-andronache** [comment]
Mie imi place mai mult a doua varianta, poate cu ultima imagine aia cu gogosile schimbata :)

**Comment by ineagu** [comment]
tot nu sunt convins, cred ca imaginile cu prajiturile nu ajuta asa mult, as
pune ceva gen niste rochii/haine sa se vada mai clar ca e shop.

apoi ca si layout ideal am scoate ceva de genu :
https://wordpress.org/themes/bazaar-lite/ , cu produsele o idee mai sus.
Poate sa mai incerce si claudiu ceva, cred ca se poate mai bine :D

On Mon, Jun 6, 2016 at 5:13 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> Mie imi place mai mult a doua varianta, poate cu ultima imagine aia cu
> gogosile schimbata :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-223971148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DIGBUSPqvbD6M064sS_rSPnvXPwrks5qJCsXgaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
Sa ne folosim chiar de dummy data de la woocommerce? Poate nu ar fi neaparat o chestie rea pentru ca lumea e familiara cu ce e acolo.

**Comment by ineagu** [comment]
e o idee si asta

2016-06-07 13:10 GMT+03:00 Andrei Băicuș <notifications@github.com>:

> Sa ne folosim chiar de dummy data de la woocommerce? Poate nu ar fi
> neaparat o chestie rea pentru ca lumea e familiara cu ce e acolo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-224237307>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DO5u_oNR8Sjx4D125B-k8qvC3bKzks5qJUN-gaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
![screenshot_0006](https://cloud.githubusercontent.com/assets/15010186/15856264/2497d1fa-2cbd-11e6-8ef2-1edabb2fb1be.png)
![screenshot_0007](https://cloud.githubusercontent.com/assets/15010186/15856266/24b1d6fe-2cbd-11e6-945e-8e78635fbcfb.png)
![screenshot_0008](https://cloud.githubusercontent.com/assets/15010186/15856267/24c312ac-2cbd-11e6-972e-225b0663638c.png)
![screenshot_0009](https://cloud.githubusercontent.com/assets/15010186/15856268/24c69efe-2cbd-11e6-96f0-20576bf76f1e.png)
![wporg_0006](https://cloud.githubusercontent.com/assets/15010186/15856272/2a0db6f4-2cbd-11e6-9dd0-35c548ec238a.jpg)
![Uploading wporg_0007.jpg…]()
![Uploading wporg_0008.jpg…]()
![Uploading wporg_0009.jpg…]()

**Comment by ineagu** [comment]
pare ok, ar cevac o fata blonda in header :D

On Tue, Jun 7, 2016 at 2:36 PM, Andrei Băicuș <notifications@github.com>
wrote:

> [image: screenshot_0006]
> <https://cloud.githubusercontent.com/assets/15010186/15856264/2497d1fa-2cbd-11e6-8ef2-1edabb2fb1be.png>
> [image: screenshot_0007]
> <https://cloud.githubusercontent.com/assets/15010186/15856266/24b1d6fe-2cbd-11e6-945e-8e78635fbcfb.png>
> [image: screenshot_0008]
> <https://cloud.githubusercontent.com/assets/15010186/15856267/24c312ac-2cbd-11e6-972e-225b0663638c.png>
> [image: screenshot_0009]
> <https://cloud.githubusercontent.com/assets/15010186/15856268/24c69efe-2cbd-11e6-96f0-20576bf76f1e.png>
> [image: wporg_0006]
> <https://cloud.githubusercontent.com/assets/15010186/15856272/2a0db6f4-2cbd-11e6-9dd0-35c548ec238a.jpg>
> [Uploading wporg_0007.jpg…]()
> [Uploading wporg_0008.jpg…]()
> [Uploading wporg_0009.jpg…]()
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle-wporg/issues/4#issuecomment-224254569>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DCMhGG5qjAq6Vk6mfMV6gBLqbLU2ks5qJVengaJpZM4IczMY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
Vin acum: :+1: 

![screenshot_0010](https://cloud.githubusercontent.com/assets/15010186/15858803/0d7c47b8-2ccb-11e6-9001-ce03cdf27fe9.png)
![screenshot_0011](https://cloud.githubusercontent.com/assets/15010186/15858807/0d7f1b6e-2ccb-11e6-851e-5896ed632384.png)
![screenshot_0012](https://cloud.githubusercontent.com/assets/15010186/15858806/0d7eca2e-2ccb-11e6-9fe3-13f8c74f5513.png)
![wporg_0010](https://cloud.githubusercontent.com/assets/15010186/15858805/0d7ed28a-2ccb-11e6-9af7-196185c42a90.jpg)
![wporg_0011](https://cloud.githubusercontent.com/assets/15010186/15858802/0d7c2378-2ccb-11e6-9869-50e2851b0ce6.jpg)
![wporg_0012](https://cloud.githubusercontent.com/assets/15010186/15858804/0d7da414-2ccb-11e6-8401-a887c3d9a7c6.jpg)

**Comment by rodica-andronache** [comment]
@abaicus here if it's ok, you can add the screenshot in the theme, and close this issue :)

**Comment by abaicus** [comment]
@ineagu: 1,2 or 3? Which of these?

**Comment by ineagu** [comment]
1
