### ISSUE TITLE
improve screenshot

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle-wporg#57]
@rodica-andronache @abaicus I think here we can improve screenshot slightly : by changing the title: 

Instead of SHOP, we can have : THIS IS JUST THE SHOP PAGE or something a bit longer and more catchy .

I have also did some tests and found that we can have a different approach for the screenshot : https://dl.kraken.io/web/38/39d43700c44d13411a6f03f6938c18/Screenshot%20at%20Jul%2027%2010-54-14.png .

In my example we can get rid of description, have better product images and use the original blonde girl in the header, what do you think ?

My worry with initial screenshot is that users can't see that theme is more complex, in 2nd we show some reviews, pricing slider and looks a bit more elegant.

In order to get the screenshot I just tried ctrl+- on the shop page.

**Comment by ineagu** [comment]
uitati cam cum ar veni daca vi se pare ca are potential : https://dl.kraken.io/web/dc/e8ca35837a35f04220b8e5f1613010/Screenshot%20at%20Jul%2027%2011-06-04.png


Stiu ca am zis ca e ok initialul, dar cred ca se poate mai bine 💃

**Comment by rodica-andronache** [comment]
@ineagu nu putem vedea imaginea

**Comment by ineagu** [comment]
<img width="1108" alt="screenshot at jul 27 11-06-04" src="https://cloud.githubusercontent.com/assets/1849868/17211197/49a61208-54c8-11e6-8bc8-0648226b91cc.png">
<img width="1034" alt="screenshot at jul 27 10-54-14" src="https://cloud.githubusercontent.com/assets/1849868/17211198/49a81c6a-54c8-11e6-9e0c-dd831c66204f.png">

**Comment by abaicus** [comment]
Pai si pastram tipa veche sau cum?

**Comment by ineagu** [comment]
Tipa veche

**Comment by abaicus** [comment]
Ce zici de astea ? 
![v1](https://cloud.githubusercontent.com/assets/15010186/17214891/9de5843c-54e3-11e6-9a2d-008f7f3f14c7.png)
![v2](https://cloud.githubusercontent.com/assets/15010186/17214892/9e07e8b0-54e3-11e6-9df3-4773cc21ada0.png)
![v3](https://cloud.githubusercontent.com/assets/15010186/17214893/9e283174-54e3-11e6-8cfa-8d74d03b81af.png)

**Comment by ineagu** [comment]
mai manareste niste margini in header image si mai da un scroll, as vrea sa prindem jos pana la nume produsului, ca la mine in screenshot, uite cum se vede pe w.org : https://www.dropbox.com/s/0g8mjnzynuc3jzd/Screenshot%202016-07-28%2015.59.42.png?dl=0

**Comment by abaicus** [comment]
![ss_placement](https://cloud.githubusercontent.com/assets/15010186/17217123/ea55fccc-54eb-11e6-98ce-f919308ea73d.jpg)
![vf](https://cloud.githubusercontent.com/assets/15010186/17217124/ea708d44-54eb-11e6-990f-1dc2e804df02.png)

**Comment by rodica-andronache** [comment]
@abaicus don't forget here also the links for each image, for readme

**Comment by rodica-andronache** [comment]
@ineagu it's ok?

**Comment by ineagu** [comment]
is fine, just hover over an image to have the add to cart butotn.

**Comment by abaicus** [comment]
HEADER: 
https://images.unsplash.com/photo-1462804993656-fac4ff489837?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=97f0f0de387332067456ca7fdda56b7b

1st product:
https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=6423a9a76d58d977ce7b5654e955ae5f

2nd product:
https://images.unsplash.com/photo-1467838371285-0d488e371f0d?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=8fe5f9c8bccc33da8b5e6575d6e9f7a4

3rd product:
https://images.unsplash.com/photo-1469460340997-2f854421e72f?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=3f23e6dac64214e7c693810058aae58f

Bottom 3:
https://images.unsplash.com/photo-1414202251636-d05ac44c0182?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=95dd8c65b835464f99ae974dafe90b24

https://images.unsplash.com/photo-1439433547555-1f4f96513499?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=467ca3b6420d16b68015006c77421e3b

https://images.unsplash.com/photo-1456379771252-03388b5adf1a?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=16db1495560136a1278a6e258ac7127a

**Comment by abaicus** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/15010186/17217804/58984f9e-54ee-11e6-9596-67c4e8055571.png)

**Comment by ineagu** [comment]
looks good

**Comment by abaicus** [comment]
![screenshot_final](https://cloud.githubusercontent.com/assets/15010186/17217994/f1d168b2-54ee-11e6-9d88-c61860422fcc.png)
