### ISSUE TITLE
documentation for wporg version

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle-wporg#62]
@rodica-andronache currently we are linking to the wrong documentation, few things are missing and might be rather confusing.

We need a new documentation explaining the homepage settings and not mentioning slider and such.

Here is the current one : http://docs.themeisle.com/article/184-shopisle-documentation.

**Comment by rodica-andronache** [comment]
I created a new doc for this, is not perfect, but it has the changes from the original Shop Isle and someone from support will arrange it: http://docs.themeisle.com/article/421-shop-isle-documentation-wordpress-org
